"""visit preregistrations and visit log

Revision ID: ae4a767e076f
Revises: 77301feda0df
Create Date: 2026-07-11 18:46:24.445410

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae4a767e076f"
down_revision: str | Sequence[str] | None = "77301feda0df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "visit_preregistrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("visitor_name", sa.String(), nullable=False),
        sa.Column("visitor_plate", sa.String(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("one_off", "recurring", name="prereg_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("expiration_hours", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("weekday", sa.Integer(), nullable=True),
        sa.Column("time_of_day", sa.Time(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'one_off' AND starts_at IS NOT NULL AND weekday IS NULL AND time_of_day IS NULL AND valid_from IS NULL AND valid_until IS NULL) OR (kind = 'recurring' AND starts_at IS NULL AND weekday IS NOT NULL AND time_of_day IS NOT NULL AND valid_from IS NOT NULL AND valid_until IS NOT NULL)",
            name=op.f("ck_visit_preregistrations_kind_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_visit_preregistrations_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_visit_preregistrations_unit_id_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visit_preregistrations")),
    )
    op.create_table(
        "visit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("visitor_name", sa.String(), nullable=False),
        sa.Column("visitor_plate", sa.String(), nullable=True),
        sa.Column("visitor_spot_id", sa.Integer(), nullable=True),
        sa.Column("guard_id", sa.Integer(), nullable=True),
        sa.Column("authorized_by_id", sa.Integer(), nullable=True),
        sa.Column("preregistration_id", sa.Integer(), nullable=True),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "authorized_by_id IS NOT NULL OR preregistration_id IS NOT NULL",
            name=op.f("ck_visit_log_authorization_present"),
        ),
        sa.ForeignKeyConstraint(
            ["authorized_by_id"],
            ["users.id"],
            name=op.f("fk_visit_log_authorized_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["guard_id"],
            ["users.id"],
            name=op.f("fk_visit_log_guard_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["preregistration_id"],
            ["visit_preregistrations.id"],
            name=op.f("fk_visit_log_preregistration_id_visit_preregistrations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_visit_log_unit_id_units"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["visitor_spot_id"],
            ["visitor_parking_spots.id"],
            name=op.f("fk_visit_log_visitor_spot_id_visitor_parking_spots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visit_log")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visit_log")
    op.drop_table("visit_preregistrations")
    # ### end Alembic commands ###
