"""infraction types and charges

Revision ID: d406fa36647e
Revises: cc3c3770dc7a
Create Date: 2026-07-12 20:35:01.238629

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d406fa36647e"
down_revision: str | Sequence[str] | None = "cc3c3770dc7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "infraction_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("fine_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fine_amount > 0", name=op.f("ck_infraction_types_fine_amount_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_infraction_types")),
        sa.UniqueConstraint("name", name=op.f("uq_infraction_types_name")),
    )
    op.create_table(
        "charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "maintenance",
                "reservation",
                "fine",
                name="charge_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=True),
        sa.Column("infraction_type_id", sa.Integer(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (paid_at IS NOT NULL AND voided_at IS NOT NULL)",
            name=op.f("ck_charges_paid_or_voided"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_charges_amount_positive")),
        sa.ForeignKeyConstraint(
            ["infraction_type_id"],
            ["infraction_types.id"],
            name=op.f("fk_charges_infraction_type_id_infraction_types"),
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_charges_reservation_id_reservations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
            name=op.f("fk_charges_unit_id_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_charges")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("charges")
    op.drop_table("infraction_types")
    # ### end Alembic commands ###
