"""buildings, units, visitor parking, unit-scoped roles with tenancy dates

Revision ID: b09a82d5ed46
Revises: a7f464c22163
Create Date: 2026-07-11 16:37:53.723524

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b09a82d5ed46"
down_revision: str | Sequence[str] | None = "a7f464c22163"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
        sa.UniqueConstraint("name", name=op.f("uq_buildings_name")),
    )
    op.create_table(
        "visitor_parking_spots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visitor_parking_spots")),
        sa.UniqueConstraint("number", name=op.f("uq_visitor_parking_spots_number")),
    )
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("apartment", "house", name="unit_kind", native_enum=False),
            nullable=False,
        ),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'apartment' AND building_id IS NOT NULL AND floor IS NOT NULL) OR (kind = 'house' AND building_id IS NULL AND floor IS NULL)",
            name=op.f("ck_units_kind_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_units_building_id_buildings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint(
            "building_id",
            "number",
            name=op.f("uq_units_building_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.add_column("role_assignments", sa.Column("unit_id", sa.Integer(), nullable=True))
    op.add_column("role_assignments", sa.Column("starts_on", sa.Date(), nullable=True))
    op.add_column("role_assignments", sa.Column("ends_on", sa.Date(), nullable=True))
    op.drop_constraint(
        op.f("uq_role_assignments_user_id"), "role_assignments", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_role_assignments_user_id"),
        "role_assignments",
        ["user_id", "role", "unit_id"],
        postgresql_nulls_not_distinct=True,
    )
    op.create_foreign_key(
        op.f("fk_role_assignments_unit_id_units"),
        "role_assignments",
        "units",
        ["unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # Check constraints on an existing table are not detected by autogenerate.
    op.create_check_constraint(
        "role_scope",
        "role_assignments",
        "(role IN ('admin', 'guard') AND unit_id IS NULL"
        " AND starts_on IS NULL AND ends_on IS NULL)"
        " OR (role = 'owner' AND unit_id IS NOT NULL"
        " AND starts_on IS NULL AND ends_on IS NULL)"
        " OR (role = 'tenant' AND unit_id IS NOT NULL"
        " AND starts_on IS NOT NULL AND ends_on IS NOT NULL)",
    )
    op.create_check_constraint(
        "tenancy_range",
        "role_assignments",
        "ends_on IS NULL OR ends_on >= starts_on",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_role_assignments_tenancy_range"), "role_assignments", type_="check"
    )
    op.drop_constraint(
        op.f("ck_role_assignments_role_scope"), "role_assignments", type_="check"
    )
    op.drop_constraint(
        op.f("fk_role_assignments_unit_id_units"),
        "role_assignments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("uq_role_assignments_user_id"), "role_assignments", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_role_assignments_user_id"),
        "role_assignments",
        ["user_id", "role"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("role_assignments", "ends_on")
    op.drop_column("role_assignments", "starts_on")
    op.drop_column("role_assignments", "unit_id")
    op.drop_table("units")
    op.drop_table("visitor_parking_spots")
    op.drop_table("buildings")
    # ### end Alembic commands ###
